---
#Begining of statement begins with -
# package is a mod in anaible is a generic OS package manager - Use the correct one for pecific servers after gathering facts
- hosts: all
  become: true
  tasks:

  - name: install apache and php 
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes


  
